//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int customerId { get; set; }
        public string customerName { get; set; }
        public string pass { get; set; }
        public int walletAmt { get; set; }
        public string phoneNo { get; set; }
        public string addres { get; set; }
    }
}
